### ISSUE TITLE
额这没有输出结果保存为txt文本的，webshell下执行一般看不到输出的这不太好

### ISSUE THREAD

**Issue by Challengers-win** [sairson/FscanX#1]

**Comment by sairson** [comment]
这个我会尽量添加，下一个版本就会更改这个问题，并且我将对一些常见服务的利用增加便利，并且我会修补一些bug，以满足能更好的在内网中使用

**Comment by AuFeng111** [comment]
> 这个我会尽量添加，下一个版本就会更改这个问题，并且我将对一些常见服务的利用增加便利，并且我会修补一些bug，以满足能更好的在内网中使用

回复下作者，这个输出的形式的确不太好，以ip:port、ip:port的形式输出例如（127.0.01:8080，127.0.0.1:9999）会比较好。

**Comment by sairson** [comment]
这个我似乎考虑到了，但是我发现，这样会在命令行产生大量的数据，由于没有颜色的输出，我觉得这样可能看起来有点混乱，我会尽量完善它，并接受你的建议，感谢
