### ISSUE TITLE
go build error

### ISSUE THREAD

**Issue by nu0l** [sairson/FscanX#4]
![image](https://user-images.githubusercontent.com/54735907/144166298-2cdaac5d-b65b-4552-ada4-67cb979fade0.png)

**Comment by sairson** [comment]
[FscanX.zip](https://github.com/sairson/FscanX/files/7633712/FscanX.zip)
可能是我在git的时候，对源码的上传出现了问题，这里我给你打包了一份我开发时候的代码，你可以尝试一下

**Comment by nu0l** [comment]
> FscanX.zip

已解决
